### ISSUE TITLE
Error in compiling

### ISSUE THREAD

**Issue by MarcAnt01** [rabiet/N26-UWP#4]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\Filippo\AppData\Local\Temp\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.	N26

**Comment by rabiet** [comment]
This issue is now fixes with the exclusion of LiveCharts and the removal of the Savings and Invest feature

**Comment by MarcAnt01** [comment]
Happy to see that the app is being worked again
